// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateParticipantName() {
  return window['go']['main']['App']['GenerateParticipantName']();
}

export function GetHumanParticipantName() {
  return window['go']['main']['App']['GetHumanParticipantName']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemPrompt(arg1) {
  return window['go']['main']['App']['GetSystemPrompt'](arg1);
}

export function GetTranscript() {
  return window['go']['main']['App']['GetTranscript']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListRules() {
  return window['go']['main']['App']['ListRules']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReloadContext() {
  return window['go']['main']['App']['ReloadContext']();
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SendMessageStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessageStream'](arg1, arg2, arg3);
}

export function SetHumanParticipantName(arg1) {
  return window['go']['main']['App']['SetHumanParticipantName'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
