// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateParticipantName():Promise<string>;

export function GetHumanParticipantName():Promise<string>;

export function GetSettings():Promise<Record<string, any>>;

export function GetSystemPrompt(arg1:string):Promise<string>;

export function GetTranscript():Promise<Record<string, any>>;

export function ListAgents():Promise<Record<string, Record<string, any>>>;

export function ListRules():Promise<Array<Record<string, any>>>;

export function ListSkills():Promise<Array<Record<string, any>>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReloadContext():Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SendMessageStream(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SetHumanParticipantName(arg1:string):Promise<string>;

export function TestConnection(arg1:string):Promise<Record<string, any>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
